### ISSUE TITLE
Make error when compiling kernel

### ISSUE THREAD

**Issue by mmatongo** [mczigler/kiss-sequoia-install#1]
```*** No rule to make target '/lib/firmware/amd-ucode/microcode_amd_fam17h.bin', needed by 'drivers/base/firmware_loader/builtin/amd-ucode/microcode_amd_fam17h.bin.gen.o'.  Stop.```

**Comment by mcpcpc** [comment]
are you using my `.config` file? Seems like you are trying to load an unused firmware blob in CONFIG_EXTRA_FIRMWARE.  this parameter should only have the blobs required for your system.  

for more info on kernel firmware, refer to https://k1ss.org/wiki/kernel/firmware (also accessible via `kiss-help`).

**Comment by mmatongo** [comment]
> are you using my `.config` file? Seems like you are trying to load an unused firmware blob in CONFIG_EXTRA_FIRMWARE. this parameter should only have the blobs required for your system.
> 
> for more info on kernel firmware, refer to https://k1ss.org/wiki/kernel/firmware (also accessible via `kiss-help`).


Yes I was using your `.config`.
I got the error a number of times before.  I’m currently compiling the 5.4.48 LTS with some borrowed inspiration from your `.config` and from my void setup.

**Comment by mcpcpc** [comment]
> Yes I was using your `.config`.
> I got the error a number of times before. I’m currently compiling the 5.4.48 LTS with some borrowed inspiration from your `.config` and from my void setup.

Ok.  Removing the extra blobs and that should at least resolve your current issue.  Otherwise, you might want to start from generating a default config file and build from there (i.e. `make defconfig`).  

edit: post your `.config` if your still having issues and i can take a look

**Comment by mmatongo** [comment]
I had to scrap my old `.config`
I have KISS installed now though there seems to be a few things that I figure I can remedy as i progress.
Your guide has been incredibly helpful.

Apparently I needed to go:

`/# make mrproper`
`/# make defconfig`
`/# make localdefconfig` 
`/# make`

going like that compiled without a hitch.

If I tried to import a `.config` file without first running `make defconfig` would cause the issue errors among others.


Edit.
1.) Post compilation of Kernel 5.4.48 I am everything seems to be working, however when I run startx I get a warning just beneath the log that says;

` WARNING: Kernel has no fine descriptor comparison support: Function not implemented `



2.) I seem to face this problem every-time it seems with KISS, whenever I attempt to start X with the command `startx` I get;

`_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/misc`

`_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/TTF`

`_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/OTF’

`_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/Type1`

`_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/100dpi`

`_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/75dpi`



Also seemingly related is `(II) modeset(0): Initialising kms color map for depth 24, 8 bpc.`

**Comment by mcpcpc** [comment]
Looks like you posted this in a few locations...

1. These are all non-fatal, per the comment on GH.  Post the full xorg log or grep the log for "EE"
2. You need a WM installed and configured. Refer to the `xinit `article on the wiki: https://k1ss.org/wiki/xorg/xinit

**Comment by mmatongo** [comment]
I managed to get help resolving this, the WM wasn’t getting properly launched.
I had `sowm &`

I put `sowm ;` and that solved it.
